# Generated by Django 4.2 on 2023-04-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tag_options_alter_scope_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.tag', verbose_name='Раздел'),
        ),
    ]
